### ISSUE TITLE
inkscape not found

### ISSUE THREAD

**Issue by tomoosting** [JacekPardyak/inkscaper#1]
Hi,

I'm trying to run the test data after installing your package but get the following error:

```
Error in system("inkscape --system-data-directory", intern = TRUE) : 
  'inkscape' not found
```
I got it when running the following code:
```
svg_sf <- "https://upload.wikimedia.org/wikipedia/commons/3/30/Den_Haag_wapen.svg" %>%
  inx_svg2sf()
```

I'm running this via Rstudio on Windows. 
I'm guessing I have to indicate where inkscape is located on my machine but I can't seem to figure out how to do that.
Any suggestions?

many thanks!

**Comment by JacekPardyak** [comment]
You need to check and eventually edit value of your "Path" Environment Variable. In my case the value is "C:\Program Files\Inkscape\bin" and points to the folder where Inkscape is installed.
